[package]
name = "wildflower-codec"
version = "0.0.1"
edition = "2021"
authors = ["Daniel Cassidy <mail@danielcassidy.me.uk>"]

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
half = "2.2.1"
inflate = "0.4.5"
num_enum = ">= 0.5.11, <= 0.6"
