use crate::decode::tags::actions::constant_pool::ConstantPool;
use crate::decode::tags::actions::define_function::DefineFunction;
use crate::decode::tags::actions::define_function_2::DefineFunction2;
use crate::decode::tags::actions::get_url::GetUrl;
use crate::decode::tags::actions::get_url_2::GetUrl2;
use crate::decode::tags::actions::go_to_frame::GoToFrame;
use crate::decode::tags::actions::go_to_frame_2::GoToFrame2;
use crate::decode::tags::actions::go_to_label::GoToLabel;
use crate::decode::tags::actions::jump::Jump;
use crate::decode::tags::actions::push::Push;
use crate::decode::tags::actions::r#if::If;
use crate::decode::tags::actions::r#try::Try;
use crate::decode::tags::actions::set_target::SetTarget;
use crate::decode::tags::actions::store_register::StoreRegister;
use crate::decode::tags::actions::wait_for_frame::WaitForFrame;
use crate::decode::tags::actions::wait_for_frame_2::WaitForFrame2;
use crate::decode::tags::actions::with::With;

#[derive(Clone, PartialEq, Debug)]
pub enum ActionRecord {
    GoToFrame(GoToFrame),
    GetUrl(GetUrl),
    NextFrame,
    PreviousFrame,
    Play,
    Stop,
    ToggleQuality,
    StopSounds,
    WaitForFrame(WaitForFrame),
    SetTarget(SetTarget),
    GoToLabel(GoToLabel),
    Push(Push),
    Pop,
    Add,
    Subtract,
    Multiply,
    Divide,
    Equals,
    Less,
    And,
    Or,
    Not,
    StringEquals,
    StringLength,
    StringAdd,
    StringExtract,
    StringLess,
    MbStringLength,
    MbStringExtract,
    ToInteger,
    CharToAscii,
    AsciiToChar,
    MbCharToAscii,
    MbAsciiToChar,
    Jump(Jump),
    If(If),
    Call,
    GetVariable,
    SetVariable,
    GetUrl2(GetUrl2),
    GoToFrame2(GoToFrame2),
    SetTarget2,
    GetProperty,
    SetProperty,
    CloneSprite,
    RemoveSprite,
    StartDrag,
    EndDrag,
    WaitForFrame2(WaitForFrame2),
    Trace,
    GetTime,
    RandomNumber,
    CallFunction,
    CallMethod,
    ConstantPool(ConstantPool),
    DefineFunction(DefineFunction),
    DefineLocal,
    DefineLocal2,
    Delete,
    Delete2,
    Enumerate,
    Equals2,
    GetMember,
    InitArray,
    InitObject,
    NewMethod,
    NewObject,
    SetMember,
    TargetPath,
    With(With),
    ToNumber,
    ToString,
    TypeOf,
    Add2,
    Less2,
    Modulo,
    BitAnd,
    BitLShift,
    BitOr,
    BitRShift,
    BitURShift,
    BitXor,
    Decrement,
    Increment,
    PushDuplicate,
    Return,
    StackSwap,
    StoreRegister(StoreRegister),
    InstanceOf,
    Enumerate2,
    StrictEquals,
    Greater,
    StringGreater,
    DefineFunction2(DefineFunction2),
    Extends,
    CastOp,
    ImplementsOp,
    Try(Try),
    Throw,
}
